In [1]:
import torch

In [4]:
data = [[1,2,3],[4,5,6]]

tensors = torch.tensor(data)

tensors

tensor([[1, 2, 3],
        [4, 5, 6]])

In [33]:
print(tensors.shape)
print(tensors.dtype)    #default is float32
print(tensors.device)

torch.Size([2, 3])
torch.int64
cpu


In [11]:
shape = (2,3)

ones = torch.ones(2,3)
zeros = torch.zeros(2,3)
rands = torch.rand(2,3)


print(zeros)
print(ones)
print(rands)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0.7907, 0.9044, 0.6958],
        [0.5264, 0.9050, 0.0690]])


In [28]:
template = torch.tensor([[1,2,3],[4,5,6]])


new_tensor = torch.randn_like(template, dtype=torch.float)

print(new_tensor)

tensor([[-0.8726, -1.3681,  0.1603],
        [ 0.3182,  2.3553, -0.2369]])


data vs parameter

In [44]:
x_data = torch.tensor([[1,2],[3,4]])

print(x_data)
w = torch.tensor([[1.0],[2.0]], requires_grad=True)
print(w)

print(w.shape)
print(w.dtype)



tensor([[1, 2],
        [3, 4]])
tensor([[1.],
        [2.]], requires_grad=True)
torch.Size([2, 1])
torch.float32


# Building the Graph

In [48]:
# <!--  z = x*y , y = a + b -->

a = torch.tensor([4.0], requires_grad=True)
b = torch.tensor([5.0], requires_grad=True)
x = torch.tensor([6.0], requires_grad=True)


y = a + b

z = x * y

print(y)
print(z)


tensor([9.], grad_fn=<AddBackward0>)
tensor([54.], grad_fn=<MulBackward0>)


In [53]:
print(f"grad_fn for a is {a.grad_fn}")   #coz in defines as a variable not funtion

print(f"grad_fn for y is {y.grad_fn}")
print(f"grad_fn for z is {z.grad_fn}")

grad_fn for a is None
grad_fn for y is <AddBackward0 object at 0x0000021E64A09730>
grad_fn for z is <MulBackward0 object at 0x0000021E6490ACD0>


### Element-wise vs Matrix multiplicatin

Element wise Multiplication
* Multiplies mathces position
* tensors must have same shape 

In [55]:
a = torch.tensor([[1,2],[3,4]])
b = torch.tensor([[10,20],[30,40]])

mul = a * b  #1*10, 2*20, 3*30, 4*40

mul

tensor([[ 10,  40],
        [ 90, 160]])

Matrix multiplication powers the newral networks

* m1 columns = m2 rows

In [56]:
matrix_mul = a @ b
matrix_mul

tensor([[ 70, 100],
        [150, 220]])

In [60]:
m1 = torch.tensor([[1,2,3],[4,5,6]])  #2 X 3
m2 = torch.tensor([[7,8],[9,10],[11,12]])  # 3 X 2

print(m1@m2)

tensor([[ 58,  64],
        [139, 154]])


 to write the linear equation 

* y = mx + c represeted as y = m @ x + c

### Reduction Operators with dim arguments

In [62]:
scores = torch.tensor([[10.,20.,30.],[5.,6.,7.,]])  # 2 X 3

avg_per_assign = scores.mean(dim=0)  # columns
avg_per_stud   = scores.mean(dim=1)  # rows

print(avg_per_assign)
print(avg_per_stud)

tensor([ 7.5000, 13.0000, 18.5000])
tensor([20.,  6.])


* argmax

In [ ]:
scores = torch.tensor([[10, 0, 5, 20, 1],
                       [1, 30, 2, 5, 0]])

best_indices = torch.argmax(scores, dim=1)  #max values of each row

print(best_indices)

tensor([3, 1])


In [85]:
scores[0][0]

tensor(10)

torch.gather()

In [87]:
data = torch.tensor([
    [10, 11, 12, 13],
    [20, 21, 22, 23],
    [30, 31, 32, 33]
])

indices_to_select = torch.tensor([[2], [0], [3]])

selected_values = torch.gather(data, dim=1, index=indices_to_select)

selected_values

# tensor([[12],  for row 0, it got indext 2
#         [20],  for row 1, it got indext 0
#         [33]]) for row 2, it got indext 3

tensor([[12],
        [20],
        [33]])