In [ ]:
!pip install torch torchvision

In [1]:
import torch
print(torch.__version__)

2.7.1+cpu


In [4]:
print(torch.version.cuda)

None


In [5]:
print(torch.cuda.is_available())

False


In [6]:
print(torch.cuda.current_device())

AssertionError: Torch not compiled with CUDA enabled

In [8]:
import torch

x = torch.empty(2)

x

tensor([0., 0.])

In [20]:
x = torch.empty(4,4,4)
x

tensor([[[2.4388e+29, 1.7558e-42, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]],

        [[0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
         [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]]])

In [18]:
x.dtype
# x.is_floating_point

torch.float32

In [30]:
x = torch.rand(2,3,dtype=torch.float16)
x

tensor([[0.5703, 0.9268, 0.5044],
        [0.2129, 0.9229, 0.5200]], dtype=torch.float16)

In [46]:
zeors = torch.zeros(2,3,dtype=torch.float16)
print(zeors)
print('tensor type;', zeors.type())

ones =torch.ones(2,3)
print(ones)
print(ones.size())


tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float16)
tensor type; torch.HalfTensor
tensor([[1., 1., 1.],
        [1., 1., 1.]])
torch.Size([2, 3])


In [47]:
t = torch.tensor([[1,2,3],[4,5,6]], dtype=float)
print(t)

print(t.dtype)

t.type() #variable type

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.float64


'torch.DoubleTensor'

Basic Operations

In [59]:
import torch

x = torch.rand(2,2)
y = torch.rand(2,2)

z = x + y

print(z)

z = torch.add(x,y)
print(z)

y.add_(x)
print(y)

print(z == y)

tensor([[0.6389, 0.8260],
        [1.6196, 1.1855]])
tensor([[0.6389, 0.8260],
        [1.6196, 1.1855]])
tensor([[0.6389, 0.8260],
        [1.6196, 1.1855]])
tensor([[True, True],
        [True, True]])


In [61]:
a = torch.rand(2,2)
b = torch.rand(2,2)

c = a - b
print(c)

c = torch.sub(a,b)
print(c)

c = a.sub_(b)
print(c)


"""
same way for div, mul
"""


tensor([[-0.0783,  0.0324],
        [ 0.2370, -0.2159]])
tensor([[-0.0783,  0.0324],
        [ 0.2370, -0.2159]])
tensor([[-0.0783,  0.0324],
        [ 0.2370, -0.2159]])


Slicing

In [77]:
x = torch.rand(3,3)
print(x)

print(x[0:2, 0:2])


# getting item
print(x[1,1].item())

#view
y = x.view(9)
y

y = x.view(-1, 3)
y


tensor([[0.2492, 0.6524, 0.7874],
        [0.8181, 0.1948, 0.6853],
        [0.5114, 0.8879, 0.1685]])
tensor([[0.2492, 0.6524],
        [0.8181, 0.1948]])
0.19481176137924194


tensor([[0.2492, 0.6524, 0.7874],
        [0.8181, 0.1948, 0.6853],
        [0.5114, 0.8879, 0.1685]])

numpy -> tensor vise versa

* if the objects of the numpy and tensor is on cpu both share the same location

In [ ]:
a = torch.ones(5)
print(a, a.type())

b = a.numpy()
print(b, type(b))


a.add_(5) # adding 5 more ones
print(a)
print(b)

tensor([1., 1., 1., 1., 1.]) torch.FloatTensor
[1. 1. 1. 1. 1.] <class 'numpy.ndarray'>
tensor([6., 6., 6., 6., 6.])
[6. 6. 6. 6. 6.]


In [85]:
import numpy as np

In [ ]:
a = np.ones(5)
# print(a)

b = torch.from_numpy(a)
# print(b)

a = a+1
print(a)

b = torch.from_numpy(a)
print(b)

b.add_(4)

print(a)   # both are accessing the same memory and any modifications reflecting to that shared memory
print(b)


[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[6. 6. 6. 6. 6.]
tensor([6., 6., 6., 6., 6.], dtype=torch.float64)


Gradients
* needed for model optimization

In [ ]:
# autograd

import torch

x = torch.rand(3, requires_grad=True)
print('x-ten',x)

y = x+2 
print('y-ten',y)

z = y*y*2
# z = z.mean()
print('z-ten', z)

v = torch.tensor([0.1, 1.0, 0.001], dtype=float)
z.backward(v) #dz/dx. # this only works for the scaler values i.e z.mean() or if z is vector, we neet to pass other vec to make it a dot product(joccovian dot product)
print(x.grad)

x-ten tensor([0.7591, 0.5699, 0.6625], requires_grad=True)
y-ten tensor([2.7591, 2.5699, 2.6625], grad_fn=<AddBackward0>)
z-ten tensor([15.2257, 13.2088, 14.1780], grad_fn=<MulBackward0>)
tensor([ 1.1037, 10.2796,  0.0107])


In [ ]:
x = torch.randn(3, requires_grad=True)
print(x)

# x.requires_grad_(False) #with this functino we can make a tensor not to use grad any time
# x.detach()
#this allows not to use grad() fnc
with torch.no_grad():
    y = x+2
    print(y)

print('with gradient')
y = x + 2
print(y)

tensor([-1.2519, -1.5072,  0.2213], requires_grad=True)
tensor([0.7481, 0.4928, 2.2213])
with gradient
tensor([0.7481, 0.4928, 2.2213], grad_fn=<AddBackward0>)


In [122]:
# During the training the backword() function passes the grad values of the iteration
# So, we need to make the grad func empty for every iteration, make sure it doesnot carry the previous grad values

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
    model_output = (weights*3).sum()
    
    model_output.backward()

    print(weights.grad)

    weights.grad.zero_() #this stops the previous iterations grad values that effects the current ones

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
